$ANSIBLE_VAULT;1.1;AES256
39666661643861663361346463336139336435626536663235313737353865383630653534616364
6532356536623632643331313331363538303834643164300a316264666231333636623630333966
38626465383838623538613037343938356537646632386534333761373733663336653265633564
3466643134633432610a366439306331613736373931306664396239326163343432636437313533
61356336376466393066353431643037636336393836633531666534613261653730323836666433
33303438663334373134333230366463623031336537623865626336356433323863656434326266
65633464316333636666356630653636646365363839373161333663333166366461306162373636
31356264396234633836623665363438356439653737646261353435616261363837316136393731
31626239393230383338373230353537326666366265656663366536663031356562613937373732
61646465313562306263343935653864636232333431386532313766303362393163353539396234
63376432396365373534333539333930636639646133393938663239373535356337333964363837
63353535663831666432
