$ANSIBLE_VAULT;1.1;AES256
38646236613336363864343539663761613265613639373235346165373930663061373237366165
3661363963636365323432383537393036356262386139330a663730666631383461313561383264
33353466353438353237306661303963303366666630623633323731666465333731303236326431
3839646636306537350a653538303237643065363130623236656131623433373664313934313363
64636633343239383061306539643561663436333130323464356230333761626163
